"""initial schema

Revision ID: 51bfb3a580a3
Revises: 
Create Date: 2026-10-01 15:03:18.837329
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '51bfb3a580a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('basis_quantity', sa.Float(), nullable=False),
    sa.Column('basis_unit', sa.String(length=24), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbohydrates_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('vitamins', sa.JSON(), nullable=False),
    sa.Column('minerals', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_normalized_name'), 'foods', ['normalized_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(length=32), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('dietary_preferences', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('intolerances', sa.JSON(), nullable=False),
    sa.Column('favorite_foods', sa.JSON(), nullable=False),
    sa.Column('avoid_foods', sa.JSON(), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('food_budget', sa.Float(), nullable=True),
    sa.Column('cultural_constraints', sa.Text(), nullable=True),
    sa.Column('daily_calorie_target', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('meals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('meal_type', sa.String(length=24), nullable=False),
    sa.Column('eaten_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meals_user_eaten_at', 'meals', ['user_id', 'eaten_at'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('water_intakes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('milliliters', sa.Float(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_intakes_user_id'), 'water_intakes', ['user_id'], unique=False)
    op.create_index('ix_water_user_consumed_at', 'water_intakes', ['user_id', 'consumed_at'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meal_id', sa.String(length=36), nullable=False),
    sa.Column('food_id', sa.String(length=36), nullable=True),
    sa.Column('food_name', sa.String(length=160), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('nutrition_snapshot', sa.JSON(), nullable=True),
    sa.Column('nutrition_known', sa.Boolean(), nullable=False),
    sa.Column('nutrition_source', sa.String(length=160), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meal_items_meal_id', 'meal_items', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meal_items_meal_id', table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index('ix_water_user_consumed_at', table_name='water_intakes')
    op.drop_index(op.f('ix_water_intakes_user_id'), table_name='water_intakes')
    op.drop_table('water_intakes')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index('ix_meals_user_eaten_at', table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_foods_normalized_name'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
